#!/bin/bash

# Set the directory to search for files with "string" in their name
SEARCH_DIR="/home/user/files"

# Search for all files with "smo" in their name and remove them
find $SEARCH_DIR -type f -name "*string*" -exec rm {} \;

#this does not work yet
